name: rdp-windows

on:
  push:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Install Scoop Package Manager
        run: |
          irm get.scoop.sh -outfile 'install.ps1'
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
      - name: add scoop shims path to PATH environment variable
        uses: myci-actions/export-env-var-powershell@1
        with:
          name: PATH
          value: $env:PATH;$env:USERPROFILE\scoop\shims
      - name: Install Scoop packages
        shell: pwsh
        run: |
          .\main\scripts\windows-scoop-packages-bore.ps1

      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      - name: Create user account
        run: cmd /c .\main\scripts\windows-user-create-org.bat
      - name: Change user password
        env:
          VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
        run: .\main\scripts\windows-user-change.ps1
      - name: Create Tunnel
        run: cmd /c "start /b bore local -p 3389 --to bore.pub 3389 > NUL"
        
      - name: Wait
        run: sleep 21000
